services:
  app:
    build:
      context: .
      dockerfile: ./docker/app/Dockerfile
    ports:
      - 3000:3000
      - 24678:24678
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - .:/app
      - node_modules_data:/app/node_modules
    networks:
      - main

  nginx:
    image: nginx:alpine
    ports:
      - 80:80
    volumes:
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - app
    networks:
      - main

networks:
  main:
    driver: bridge

volumes:
  node_modules_data:
    driver: "local"
