name: Vercel Production Deployment
env:
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
on:
  push:
    branches:
      - master
jobs:
  Deploy-Production:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Install Vercel CLI
        run: npm install --global vercel@latest
      - name: Pull Vercel Environment Information
        run: vercel env pull .env --yes --environment=production --token=${{ secrets.VERCEL_TOKEN }}
      - name: Fix Vercel Environment Information
        run: grep -vE '^(# Created by Vercel CLI|NX_DAEMON|TURBO_DOWNLOAD_LOCAL_ENABLED|TURBO_REMOTE_ONLY|TURBO_RUN_SUMMARY|VERCEL|VERCEL_ENV|VERCEL_GIT_COMMIT_AUTHOR_LOGIN|VERCEL_GIT_COMMIT_AUTHOR_NAME|VERCEL_GIT_COMMIT_MESSAGE|VERCEL_GIT_COMMIT_REF|VERCEL_GIT_COMMIT_SHA|VERCEL_GIT_PREVIOUS_SHA|VERCEL_GIT_PROVIDER|VERCEL_GIT_PULL_REQUEST_ID|VERCEL_GIT_REPO_ID|VERCEL_GIT_REPO_OWNER|VERCEL_GIT_REPO_SLUG|VERCEL_URL)' .env > .env.temp && mv .env.temp .env
      - name: Build Project Artifacts
        run: vercel build --prod --token=${{ secrets.VERCEL_TOKEN }}
      - name: Deploy Project Artifacts to Vercel
        run: vercel deploy --prebuilt --prod --token=${{ secrets.VERCEL_TOKEN }}
